### ISSUE TITLE
can I get a credit?

### ISSUE THREAD

**Issue by fuckmyass** [onodera-punpun/ricespo#3]
This is my desktop http://camillescholtz.nl/ricespo/assets/images/rice/full/unknown_1.png, proof here https://github.com/fuckmyass/dots/tree/master/proschanie - could I get a credit? Great page, amazing rice

**Comment by onodera-punpun** [comment]
Should I just use fuckmyass? lol

**Comment by fuckmyass** [comment]
Eh, probably best to use cozmoss, my name on reddit
